version: '3.9'
services:
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 1234MMfa
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
       - SECRET_KEY=django-insecure-*@e^!9g%8+pr&g@m^##&_5+_optmgm#(cqiob=thmm66n%dxy%
       - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db